// Ported from clickbit/server/config/roles.js
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [
    'users:list',
    'users:view',
    'users:create',
    'users:update',
    'users:delete',
    'content:list',
    'content:view',
    'content:create',
    'content:update',
    'content:delete',
    'services:list',
    'services:view',
    'services:create',
    'services:update',
    'services:delete',
    'team:list',
    'team:view',
    'team:create',
    'team:update',
    'team:delete',
    'reviews:list',
    'reviews:view',
    'reviews:update',
    'reviews:delete',
    'contacts:list',
    'contacts:view',
    'contacts:delete',
    'orders:list',
    'orders:view',
    'orders:update',
    'orders:delete',
    'dashboard:view',
    'settings:view',
    'settings:update',
    'billing:view',
    'billing:update',
    'marketing:view',
    'marketing:update',
    'tasks:list_assignees',
  ],
  manager: [
    'content:list',
    'content:view',
    'content:create',
    'content:update',
    'content:delete',
    'services:list',
    'services:view',
    'services:create',
    'services:update',
    'services:delete',
    'team:list',
    'team:view',
    'team:create',
    'team:update',
    'team:delete',
    'reviews:list',
    'reviews:view',
    'reviews:update',
    'reviews:delete',
    'contacts:list',
    'contacts:view',
    'contacts:delete',
    'orders:list',
    'orders:view',
    'orders:update',
    'orders:delete',
    'dashboard:view',
    'settings:view',
    'settings:update',
    'marketing:view',
    'marketing:update',
    'tasks:list_assignees',
    'tasks:mention_colleagues',
  ],
  employee: [
    'dashboard:view',
    'hr:timeclock',
    'hr:schedule_view',
    'hr:timeoff_request',
    'hr:announcements_view',
    'contacts:list',
    'contacts:view',
    'orders:list',
    'orders:view',
    'content:list',
    'content:view',
    'team:list',
    'team:view',
    'services:list',
    'services:view',
    'tasks:list_assignees',
    'tasks:mention_colleagues',
  ],
  customer: [],
  agent: [
    'dashboard:view',
    'contacts:list',
    'contacts:view',
    'tasks:list_assignees',
    'tasks:mention_colleagues',
  ],
  user: [],
};

export const ROLE_TOKENS = ['admin', 'manager', 'customer', 'employee', 'agent'];

export const TASK_STAFF_TEMPLATE_KEYS = [
  'tasks:list_assignees',
  'tasks:mention_colleagues',
];
