import {
  Injectable,
  CanActivate,
  ExecutionContext,
  UnauthorizedException,
  InternalServerErrorException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Request } from 'express';
import jwt, { JwtPayload } from 'jsonwebtoken';
import { createClient } from '@supabase/supabase-js';
import WebSocket from 'ws';
import { PrismaService } from '../prisma/prisma.service';
import { CacheService } from '../redis/cache.service';
import { Profile } from '@clickbit/shared';

const TOKEN_CACHE_TTL_SECONDS = 60;

function isSupabaseToken(token: string): boolean {
  try {
    const decoded = jwt.decode(token, { complete: true });
    if (decoded && typeof decoded === 'object' && decoded.payload) {
      const payload = decoded.payload as JwtPayload;
      // Supabase access tokens carry a UUID subject and the authenticated role.
      // Custom JWTs generated by this app use an `id` claim instead.
      if (payload.id || payload.role !== 'authenticated') return false;
      return typeof payload.sub === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(payload.sub);
    }
  } catch {
    // If decode fails, assume it's not a Supabase token
  }
  return false;
}

function tokenTtlSeconds(token: string): number {
  try {
    const decoded = jwt.decode(token, { complete: true });
    if (decoded && typeof decoded === 'object' && decoded.payload) {
      const payload = decoded.payload as JwtPayload;
      if (typeof payload.exp === 'number' && payload.exp > 0) {
        const ttl = Math.floor(payload.exp - Date.now() / 1000);
        return ttl > 0 ? Math.min(ttl, TOKEN_CACHE_TTL_SECONDS) : 0;
      }
    }
  } catch {
    // ignore
  }
  return TOKEN_CACHE_TTL_SECONDS;
}

@Injectable()
export class SupabaseAuthGuard implements CanActivate {
  constructor(
    private config: ConfigService,
    private prisma: PrismaService,
    private cache: CacheService,
  ) {}

  private static tokenQueue = new Map<string, Promise<Profile>>();

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const request = context.switchToHttp().getRequest<Request>();
    let token: string | undefined;

    const authHeader = request.headers.authorization;
    if (authHeader && authHeader.startsWith('Bearer ')) {
      token = authHeader.split(' ')[1];
    } else if (typeof request.query?.token === 'string') {
      token = request.query.token;
    }

    if (!token) {
      throw new UnauthorizedException({
        success: false,
        message: 'Not authorized, no token',
      });
    }

    // Service tokens (cb_*) are reserved for future service-to-service auth.
    if (token.startsWith('cb_')) {
      throw new UnauthorizedException({
        success: false,
        message: 'Service token authentication not yet migrated',
      });
    }

    if (isSupabaseToken(token)) {
      const profile = await this.verifySupabaseTokenWithCache(token);
      request.user = profile;
      return true;
    }

    return this.authenticateCustomJwt(request, token);
  }

  private async verifySupabaseTokenWithCache(token: string): Promise<Profile> {
    // Serialize verification per token so concurrent requests with the same
    // access token do not hammer Supabase with parallel getUser() calls.
    const existing = SupabaseAuthGuard.tokenQueue.get(token);
    if (existing) {
      return existing;
    }

    const verification = this.verifySupabaseTokenQueued(token);
    SupabaseAuthGuard.tokenQueue.set(token, verification);
    try {
      return await verification;
    } finally {
      SupabaseAuthGuard.tokenQueue.delete(token);
    }
  }

  private async verifySupabaseTokenQueued(token: string): Promise<Profile> {
    const cacheKey = this.cache.key('auth', 'guard', token);
    const cached = await this.cache.get<Profile>(cacheKey);
    if (cached) {
      return cached;
    }

    const profile = await this.verifySupabaseToken(token);
    const ttl = tokenTtlSeconds(token);
    if (ttl > 0) {
      await this.cache.set(cacheKey, profile, ttl);
    }

    return profile;
  }

  private async verifySupabaseToken(token: string): Promise<Profile> {
    const supabaseUrl = this.config.get<string>('SUPABASE_URL');
    const supabaseServiceKey = this.config.get<string>(
      'SUPABASE_SERVICE_ROLE_KEY',
    );

    if (!supabaseUrl || !supabaseServiceKey) {
      throw new InternalServerErrorException({
        message: 'Supabase Auth is not configured',
      });
    }

    const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
      realtime: {
        transport: WebSocket as any,
      },
    });

    try {
      const { data, error } = await supabaseAdmin.auth.getUser(token);
      if (error || !data?.user) {
        throw new UnauthorizedException({
          success: false,
          message: 'Not authorized, token failed',
        });
      }

      const supabaseUser = data.user;

      let profile = await this.prisma.profiles.findFirst({
        where: { auth_uid: supabaseUser.id },
      });

      if (!profile && supabaseUser.email) {
        profile = await this.prisma.profiles.findFirst({
          where: { email: supabaseUser.email.trim() },
        });
        if (profile) {
          profile = await this.prisma.profiles.update({
            where: { id: profile.id },
            data: { auth_uid: supabaseUser.id },
          });
        }
      }

      if (!profile) {
        throw new UnauthorizedException({
          success: false,
          message: 'Not authorized, user not found',
        });
      }

      return profile as Profile;
    } catch (err) {
      if (err instanceof UnauthorizedException) {
        throw err;
      }
      console.error('Supabase token verification failed:', err);
      throw new UnauthorizedException({
        success: false,
        message: 'Not authorized, token failed',
      });
    }
  }

  private async authenticateCustomJwt(
    request: Request,
    token: string,
  ): Promise<boolean> {
    const jwtSecret = this.config.get<string>('JWT_SECRET');
    if (!jwtSecret) {
      throw new InternalServerErrorException({
        message: 'JWT secret is not configured',
      });
    }

    try {
      const decoded = jwt.verify(token, jwtSecret) as { id: number | string };
      const profile = await this.prisma.profiles.findUnique({
        where: { id: Number(decoded.id) },
      });

      if (!profile) {
        throw new UnauthorizedException({
          success: false,
          message: 'Not authorized, user not found',
        });
      }

      request.user = profile as Profile;
      return true;
    } catch (err) {
      console.error('Custom JWT verification failed:', err);
      throw new UnauthorizedException({
        success: false,
        message: 'Not authorized, token failed',
      });
    }
  }
}
