export type {
  AdminTicketListResponse,
  CannedResponse,
  CustomerRepository,
  CustomerTicketListResponse,
  StaffTicketListResponse,
  SupportStaff,
  Ticket,
  TicketListResponse,
  TicketMessage,
  TicketProfile,
  TicketPurchase,
  TicketQuota,
  TicketReplyResponse,
  TicketStats,
} from '@clickbit/shared';
