export type {
  CachedEmail,
  Channel,
  ChatProfile,
  CommunicationLegacyDataResponse,
  CommunicationLegacyListResponse,
  CommunicationLegacyMessageResponse,
  ConversationPreferences,
  CursorPagination,
  DirectMessage,
  DirectMessageParticipant,
  EmailTemplate,
  MailAccount,
  MailFolder,
  MailPreset,
  Message,
  MessageEnvelope,
  MessageListResponse,
  Reaction,
  Workspace,
  WorkspaceMember,
} from '@clickbit/shared';
